###

# curl webshop:secret@localhost:8001/oauth/token -d grant_type=password -d username=pape123 -d password=pape123 -d scope=write
POST webshop:secret@localhost:8001/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=pape123&password=pape123&scope=write

###



POST   http://localhost:8001/users/
content-type: application/json

{
  "username": "pape123",
  "firstname": "be",
  "lastname": "ju",
  "password": "pape123",
  "roletype": "admin",
  "rolelevel": 1
}
###
POST http://localhost:8003/categories
content-type: application/json

{
"name": "Kaffee",
"productIds": ""
}
###
POST  http://localhost:8081/productscomposite-service/products/
content-type: application/json

{
"name": "Koffee",
"price": 100.0,
"categoryId": 2,
"details": "Really expensive Coffee"
}
####
POST  http://localhost:8081/productscomposite-service/products/
content-type: application/json

{
  "name": "Cheaper Coffee",
  "price": 10.0,
  "categoryId": 1,
  "details": "Really cheap Coffee"
}

###
GET http://localhost:8081/productscomposite-service/products/
Cache-Control: no-cache
####